#! /bin/sh
#
### BEGIN INIT INFO
# Provides: pf9-hostagent
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the platform9 host agent
### END INIT INFO

# read & export proxy information
. /etc/environment

SHORT_NAME="hostagent"
progname="pf9-hostd"
svcname="pf9-${SHORT_NAME}"

SERVER_BIN="/opt/pf9/${SHORT_NAME}/bin/$progname"

SERVER_OPTS=""

SERVER_LOGFILE=/var/log/pf9/${SHORT_NAME}-daemon.log

PIDFILE=/var/run/${svcname}.pid
LOCKFILE=/var/lock/subsys/$svcname

# Source function library.
. /etc/init.d/functions


RETVAL=0
uid=`id | cut -d\( -f1 | cut -d= -f2`

start() {

    [ -f $SERVER_BIN ] || exit 5

    # Make sure the service is not already running.
    if status $progname > /dev/null ; then
        exit 0
    fi

    # Only root can start the service
    [ $uid -ne 0 ] && exit 4

    echo -n $"Starting $svcname: "
    touch $PIDFILE
    chown pf9:pf9group $PIDFILE
    LD_LIBRARY_PATH="/opt/pf9/python/pf9-lib:/opt/pf9/python/pf9-hostagent-lib:${LD_LIBRARY_PATH}" \
    PYTHONPATH="/opt/pf9/python/lib/python2.7:${PYTHONPATH}" \
    SYSTEMCTL_SKIP_REDIRECT=1 \
    daemon --user pf9 "$SERVER_BIN $SERVER_OPTS >> $SERVER_LOGFILE 2>&1 & echo \$! > $PIDFILE"
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ] ; then
        touch $LOCKFILE
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $svcname: "
    killproc $progname
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && {
        rm -f $LOCKFILE
        rm -f $PIDFILE
    }
    return $RETVAL
}

# See how we were called.
case "$1" in
  start)
    start
    RETVAL=$?
    ;;
  stop)
    stop
    RETVAL=$?
    ;;
  status)
    status $progname
    RETVAL=$?
    ;;
  restart | reload | force-reload)
    stop
    start
    RETVAL=$?
    ;;
  condrestart | try-restart)
    if status $progname > /dev/null; then
        stop
        start
        RETVAL=$?
    fi
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
    RETVAL=2
    ;;
esac

exit $RETVAL
