#!/bin/sh
#
### BEGIN INIT INFO
# Provides: pf9-hostagent
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the platform9 host agent
### END INIT INFO

# read & export proxy information
. /etc/environment

prog="pf9-hostagent"
svcname="pf9-hostagent"

SERVER_BIN="/opt/pf9/hostagent/bin/$prog"

SERVER_OPTS=""

SERVER_LOGFILE=/var/log/${svcname}-daemon.log

PIDFILE=/var/run/${svcname}.pid

# Source function library.
. /lib/lsb/init-functions


RETVAL=0
uid=`id | cut -d\( -f1 | cut -d= -f2`

start() {

    [ -f $SERVER_BIN ] || exit 5

    # Make sure the service is not already running.
    if status > /dev/null ; then
        log_success_msg "${svcname} is already up (PID `pidofproc -p $PIDFILE`)"
        exit 0
    fi

    # Only root can start the service
    [ $uid -ne 0 ] && exit 4

    /sbin/start-stop-daemon --start --oknodo --background --make-pidfile \
            --pidfile $PIDFILE  --quiet --startas /bin/bash -- \
            -c "exec $SERVER_BIN $SERVER_OPTS >> $SERVER_LOGFILE 2>&1"

    RETVAL=$?
    if [ "$RETVAL" -eq "0" ]; then
        log_success_msg "Started:" "$svcname"
    else
        log_failure_msg "Failed to start:" "$svcname"
    fi
    return $RETVAL
}

stop() {
    /sbin/start-stop-daemon --stop --oknodo --make-pidfile \
            --pidfile $PIDFILE --quiet --startas /bin/bash -- \
            -c "exec $SERVER_BIN $SERVER_OPTS >> $SERVER_LOGFILE 2>&1"

    RETVAL=$?
    if [ "$RETVAL" -eq "0" ]; then
        log_success_msg "Stopped:" "$svcname"
    else
        log_failure_msg "Failed to stop:" "$svcname"
    fi
    rm -f $PIDFILE
    return $RETVAL
}

status() {
    status_of_proc -p $PIDFILE $SERVER_BIN $svcname
}

# See how we were called.
case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    status)
        status
        RETVAL=$?
        ;;
    restart | reload | force-reload)
        stop
        start
        RETVAL=$?
        ;;
    condrestart | try-restart)
        if status > /dev/null; then
            stop
            start
            RETVAL=$?
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
        RETVAL=2
        ;;
esac

exit $RETVAL
