#!/opt/pf9/bbmaster/bin/python

# Copyright (c) 2014 Platform9 Systems Inc.
# All Rights Reserved.

"""
Given a unique customer short name, generates a root CA certificate for
the customer, and uses it to sign 3 certificates for rabbit broker,
backbone master, and backbone slave.

Usage: 05-generate-certs [options] customer_shortname customer_fullname
"""

from pf9cert import create_root_CA, create_certificate
from optparse import OptionParser
from os.path import join, exists
from os import makedirs
import sys


def write_key_and_cert(base_dir, svcname, key, cert):
    data = [('key.pem', key), ('cert.pem', cert)]
    dir = join(base_dir, svcname)
    if not exists(dir):
        makedirs(dir)
    for (name, buf) in data:
        fpath = join(dir, name)
        with open(fpath, 'w') as file:
            file.write(buf)
        print 'Wrote %s' % fpath

def parse_input():
    parser = OptionParser(usage="usage: %prog [options] customer_shortname customer_fullname",
                          version="%prog 1.0")
    parser.add_option("--basedir",
                      action='store',
                      dest='basedir',
                      default='/etc/pf9/certs',
                      help='Location where the generated certificate files are stored.')
    parser.add_option("--expiration-days",
                      action='store',
                      dest='exp_days',
                      default='365',
                      help='Number of days after which the certificates will expire.')
    (options, args) = parser.parse_args()

    if len(args) != 2:
        sys.stdout.write('Missing arguments.')
        parser.print_usage()
        sys.exit(1)

    return options, args

def main():
    services = [('broker', True), ('bbmaster', False), ('hostagent', False)]

    options, args = parse_input()
    base_dir = options.basedir
    cust_name = args[0]
    cust_fullname = args[1]
    days = int(options.exp_days)
    (key, cert) = create_root_CA(cust_name, cust_fullname, days)
    write_key_and_cert(base_dir, 'ca', key, cert)
    for (svcname, for_server) in services:
        (key, cert) = create_certificate(customer_id=cust_name,
                                         service_id=svcname,
                                         days=days,
                                         for_server=for_server)
        write_key_and_cert(base_dir, svcname, key, cert)

if __name__ == '__main__':
    try:
        main()
    except:
        sys.stderr.write('Certificate generation failed.')
        sys.exit(1)
