#!/bin/bash
# Copyright (c) 2014 Platform9 Systems Inc.
# All Rights reserved

# /etc/init.d/pf9-janitor

### BEGIN INIT INFO
# Provides: pf9-janitor
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: The platform9 maintenance task service
### END INIT INFO

. /etc/rc.d/init.d/functions

name=pf9-janitor
root=/opt/pf9/janitor
cmd="$root/bin/python $root/bin/janitor-daemon.py"
pidfile=/var/run/pf9/janitor.pid

case "$1" in
  start)
    echo "Starting $name"
    $cmd start
    RETVAL=$?
    ;;
  stop)
    echo "Stopping $name"
    $cmd stop
    RETVAL=$?
    ;;
  restart)
    echo "Restarting $name"
    $cmd stop
    $cmd start
    RETVAL=$?
    ;;
  condrestart)
    RETVAL=0
    if status > /dev/null 2>&1; then
      echo "Stopping $name"
      $cmd stop
      echo "Starting $name"
      $cmd start
      RETVAL=$?
    fi
    ;;
  status)
    status -p $pidfile "$cmd"
    RETVAL=$?
    ;;
  *)
    echo "Usage: /etc/init.d/pf9-janitor {start|stop|restart|condrestart|status}"
    exit 1
    ;;
esac

exit $RETVAL

