#!/bin/sh
# Copyright (c) 2014 Platform9 Systems Inc.

# This script creates the host-agent rpm by expanding the tar file
# followed by a call to embedded rpm build file
# The RPM can be acccessed by the following URLS:
# hostagent: http://<ip>/hostagent/pf9-hostagent-1.0.0-1.x86_64.rpm


set -v
set -u
set -e

usage() {
    echo "Usage: $0 <amqp_username> <amqp_password>"
    exit 1
}

[ $# != 2 ] && usage

AMQP_USER=$1
AMQP_PASS=$2

VERSION=__VERSION__
RELEASE=__BUILDNUM__.__GITHASH__
VERSION=${HOST_AGENT_VERSION:-${VERSION}}
RELEASE=${HOST_AGENT_RELEASE:-${RELEASE}}
MGMT_FQDN=${MGMT_FQDN:-${DU_FQDN}}
DU_IS_CONTAINER=${DU_IS_CONTAINER:-"false"}

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=$CURR_DIR/../
HOSTAGENT_TARBALL=$ROOT_DIR/hostagent-tarball/debian/pf9-hostagent.tar.gz
RPMBUILD_DIR=$ROOT_DIR/hostagent-tarball/debian/deb-build

HOST_AGENT_RPM_NAME=pf9-hostagent-$VERSION-$RELEASE.x86_64.deb
HOST_AGENT_RPM=$RPMBUILD_DIR/RPMS/x86_64/$HOST_AGENT_RPM_NAME
PRIVATE_FILES_DIR=$ROOT_DIR/www/private

# Create a temporary directory to expand the tarball
HOSTAGENT_TARBALL_EXPANDEDDIR=`mktemp -d -t pf9-XXX`

# Expand the tarball
tar -xzf $HOSTAGENT_TARBALL -C $HOSTAGENT_TARBALL_EXPANDEDDIR

# Copy certificates
# For backward compatibility, CERT_VERSION may be an empty string.
CERT_VERSION=
CERTS_DIR=/etc/pf9/certs
pushd ${CERTS_DIR}
if ls -vd v* > /dev/null 2>&1; then
    CERT_VERSION="$(ls -vd v* | tail -n 1)"
    CERTS_DIR="${CERTS_DIR}/${CERT_VERSION}"
fi
popd

mkdir -p $HOSTAGENT_TARBALL_EXPANDEDDIR/etc/pf9/certs
cp -r ${CERTS_DIR}/hostagent $HOSTAGENT_TARBALL_EXPANDEDDIR/etc/pf9/certs/
chmod 440 $HOSTAGENT_TARBALL_EXPANDEDDIR/etc/pf9/certs/hostagent/key.pem
mkdir -p $HOSTAGENT_TARBALL_EXPANDEDDIR/etc/pf9/certs/ca
cp ${CERTS_DIR}/ca/cert.pem $HOSTAGENT_TARBALL_EXPANDEDDIR/etc/pf9/certs/ca

#clean the RPMBUILD dir
rm -fr $RPMBUILD_DIR
mkdir $RPMBUILD_DIR

# Create the DEB
$HOSTAGENT_TARBALL_EXPANDEDDIR/hostagent-deb-build.sh $RPMBUILD_DIR $HOSTAGENT_TARBALL_EXPANDEDDIR $MGMT_FQDN $VERSION $RELEASE $AMQP_USER $AMQP_PASS $DU_IS_CONTAINER "${CERT_VERSION}"

