#!/bin/sh
# Copyright (c) 2015 Platform9 Systems Inc.

# This script creates the VMWare appliance.
# It requires the installer script to already exist.


set -v
set -u
set -e
set -x

VERSION=__VERSION__
RELEASE=__BUILDNUM__.__GITHASH__
VERSION=${HOST_AGENT_VERSION:-${VERSION}}
RELEASE=${HOST_AGENT_RELEASE:-${RELEASE}}
MGMT_FQDN=${MGMT_FQDN:-${DU_FQDN}}

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=$CURR_DIR/../

PRIVATE_FILES_DIR=$ROOT_DIR/www/private
INSTALLER_FILENAME=platform9-install-redhat.sh
INSTALLER_PATH=${PRIVATE_FILES_DIR}/${INSTALLER_FILENAME}
CUSTOMIZE_SCRIPT_DIR=/opt/pf9/du-customize/vmw_scripts
OVF_BASE_DIR=/opt/pf9/vmware
# Short name excludes extension
OVA_SHORT_NAME=platform9-vmware-appliance
OVA_NAME=${OVA_SHORT_NAME}-${VERSION}-${RELEASE}.ova
OVA_PATH=${PRIVATE_FILES_DIR}/${OVA_SHORT_NAME}-${VERSION}-${RELEASE}.ova
OVA_SYMLINK_NAME=${OVA_SHORT_NAME}.ova

ISO_NAME=hostagent.iso
ISO_PATH=${OVF_BASE_DIR}/${ISO_NAME}
ISO_STAGING_DIR=`mktemp -d`
ISO_INSTALLER_DIR=${ISO_STAGING_DIR}/installer

mkdir -p ${ISO_INSTALLER_DIR}

cp ${INSTALLER_PATH} ${ISO_INSTALLER_DIR}
cp ${CUSTOMIZE_SCRIPT_DIR}/* ${ISO_STAGING_DIR}
genisoimage -o ${ISO_PATH} -r ${ISO_STAGING_DIR}

pushd ${OVF_BASE_DIR}
VMDK_SIZE=$(stat -c '%s' ${OVA_SHORT_NAME}-disk1.vmdk)
ISO_SIZE=$(stat -c '%s' ${ISO_NAME})
# Add correct VMDK and ISO size to OVF
sed -e "s/__VMDK_SIZE__/${VMDK_SIZE}/" -e "s/__ISO_SIZE__/${ISO_SIZE}/" ${OVA_SHORT_NAME}-template.ovf > ${OVA_SHORT_NAME}.ovf
rm -f ${OVA_SHORT_NAME}-template.ovf
# Create a manifest file
openssl sha1 ${OVA_SHORT_NAME}{-disk1.vmdk,.ovf} ${ISO_NAME} > ${OVA_SHORT_NAME}.mf
# Files need to be tar'ed up in a particular order - ovf, mf, vmdk and then iso
tar -cvf ${OVA_SHORT_NAME}.ova \
         ${OVA_SHORT_NAME}{.ovf,.mf,-disk1.vmdk} \
         ${ISO_NAME}
popd

mv ${OVF_BASE_DIR}/${OVA_SHORT_NAME}.ova ${OVA_PATH}

pushd $PRIVATE_FILES_DIR
ln -sf $OVA_NAME $OVA_SYMLINK_NAME
popd

# Cleanup
rm -fr $OVF_BASE_DIR
rm -fr $ISO_STAGING_DIR

