#!/bin/bash
# Copyright (c) 2014 Platform9 Systems Inc.
# All Rights reserved

# /etc/init.d/pf9-resmgr

### BEGIN INIT INFO
# Provides: pf9-resmgr
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: The platform9 resource manager
### END INIT INFO

name=pf9-resmgr
root=/opt/pf9/resmgr
cmd="$root/bin/python $root/bin/resmgr-daemon.py"
pidfile=/var/run/pf9/resmgr.pid

status() {
    if [ ! -e $pidfile ]; then
        echo "$name service is not running"
        return 1
    elif ! kill -0 `cat $pidfile` >> /dev/null 2>&1; then
        rm -f $pidfile
        echo "$name service is not running"
        return 1
    else
        echo "$name service is running"
        return 0
    fi
}

case "$1" in
  start)
    echo "Starting $name"
    $cmd start
    RETVAL=$?
    ;;
  stop)
    echo "Stopping $name"
    $cmd stop
    RETVAL=$?
    ;;
  restart)
    echo "Restarting $name"
    $cmd stop
    $cmd start
    RETVAL=$?
    ;;
  condrestart)
    RETVAL=0
    if status > /dev/null 2>&1; then
      echo "Stopping $name"
      $cmd stop
      echo "Starting $name"
      $cmd start
      RETVAL=$?
    fi
    ;;
  status)
    status
    RETVAL=$?
    ;;
  *)
    echo "Usage: /etc/init.d/pf9-resmgr {start|stop|restart|condrestart|status}"
    exit 1
    ;;
esac

exit $RETVAL

