#!/bin/bash
# Copyright (c) 2014 Platform9 Systems Inc.
# All Rights reserved

# /etc/init.d/pf9-resmgr

### BEGIN INIT INFO
# Provides: pf9-resmgr
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: The platform9 resource manager
### END INIT INFO

name=pf9-resmgr
root=/opt/pf9/resmgr
cmd="$root/bin/python $root/bin/resmgr-daemon.py"
pidfile=/var/run/pf9/resmgr.pid

case "$1" in
  start)
    echo "Starting $name"
    $cmd start
    ;;
  stop)
    echo "Stopping $name"
    $cmd stop
    ;;
  restart)
    echo "Restarting $name"
    $cmd restart
    ;;
  status)
    if [ ! -e $pidfile ]; then
        echo "$name service is not running"
        exit 1
    elif ! kill -0 `cat $pidfile` >> /dev/null 2>&1; then
        rm -f $pidfile
        echo "$name service is not running"
        exit 1
    else
        echo "$name service is running"
        exit 0
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/pf9-resmgr {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

