#! /bin/sh
#
### BEGIN INIT INFO
# Provides: pf9-bbmaster
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: The platform9 backbone master
### END INIT INFO

# read & export proxy information
. /etc/environment

SHORT_NAME="bbmaster"
svcname="pf9-${SHORT_NAME}"
BIN_DIR=/opt/pf9/${SHORT_NAME}/bin
prog="${BIN_DIR}/${svcname}"

PIDFILE=/var/run/${svcname}.pid
SERVER_BIN="$prog"

SERVER_OPTS="${BIN_DIR}/pecan serve /etc/pf9/bbmaster_config.py"

SERVER_LOGFILE=/var/log/pf9/${SHORT_NAME}-out.log

LOCKFILE=/var/lock/subsys/$svcname

# Source function library.
. /etc/init.d/functions


RETVAL=0
uid=`id | cut -d\( -f1 | cut -d= -f2`

start() {

    [ -f $SERVER_BIN ] || exit 5

    # Make sure the service is not already running.
    if status $prog > /dev/null; then
        echo "${svcname} is already up (pid `pidofproc $prog`)"
        exit 0
    fi

    # Only root can start the service
    [ $uid -ne 0 ] && exit 4

    echo -n $"Starting $svcname: "
    touch "$SERVER_LOGFILE"
    daemon "$SERVER_BIN $SERVER_OPTS >> $SERVER_LOGFILE 2>&1 & echo \$! > ${PIDFILE}"
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ] ; then
        touch ${LOCKFILE}
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping $svcname: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && {
        rm -f ${LOCKFILE}
        rm -f ${PIDFILE}
    }
    return $RETVAL
}

# See how we were called.
case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    status)
        status $prog
        RETVAL=$?
        ;;
    restart | reload | force-reload)
        stop
        start
        RETVAL=$?
        ;;
    condrestart | try-restart)
        if status $prog > /dev/null; then
            stop
            start
            RETVAL=$?
        fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
        RETVAL=2
        ;;
esac

exit $RETVAL
