#!/bin/bash
# Copyright (c) 2015 Platform9 Systems Inc.

if [[ $UID -ne 0 ]]; then
    echo "$0 must be run as root"
    exit 1
fi

echo ""
echo "Extracting Platform9 installer"
echo ""

export TMPDIR=`mktemp -d /tmp/pf9-install-XXXXX`

ARCHIVE=`awk '/^__PF9_ARCHIVE__/ {print NR + 1; exit 0; }' "$0"`

tail -n+$ARCHIVE "$0" | tar xzv -C $TMPDIR > /dev/null

cd $TMPDIR
./installer "$@"

exit $?

__PF9_ARCHIVE__
