[template]
src = 'bbmaster.conf'
dest = '/etc/pf9/bbmaster.conf'
owner = 'root'
mode = '0644'
keys = [
    '/rabbit_broker/users/bbmaster/username',
    '/rabbit_broker/users/bbmaster/password'
]
#reload_cmd = 'supervisorctl restart bbmaster'
