[template]
src = 'bbmaster.conf'
dest = '/etc/pf9/bbmaster.conf'
owner = 'root'
mode = '0644'
keys = [
    '/rabbit_broker/users',
    '/environment',
    '/services/bbmaster',
]
reload_cmd = 'supervisorctl restart bbmaster'
