[template]
src = 'hostagent.conf'
dest = '/opt/pf9/www/private/etc/pf9/hostagent.conf'
owner = 'root'
mode = '0644'
keys = [
    '/services/resmgr/rabbit_users/bbslave/user',
    '/services/resmgr/rabbit_users/bbslave/passwd',
    '/certs/current_version',
    '/fqdn'
]
