[template]
src = 'hostagent-cert.pem'
dest = '/opt/pf9/www/private/etc/pf9/certs/hostagent/cert.pem'
owner = 'root'
mode = '0644'
keys = [
    '/certs/current_version',
    '/certs/v0/hostagent/cert',
    '/certs/v1/hostagent/cert',
    '/certs/v2/hostagent/cert',
    '/certs/v3/hostagent/cert',
    '/certs/v4/hostagent/cert',
    '/certs/v5/hostagent/cert',
    '/certs/v6/hostagent/cert',
    '/certs/v7/hostagent/cert',
    '/certs/v8/hostagent/cert',
    '/certs/v9/hostagent/cert'
]
