[template]
src = 'resmgr-paste.ini'
dest = '/etc/pf9/resmgr-paste.ini'
owner = 'pf9'
mode = '0644'
keys = [
    '/services/resmgr',
    '/region_id',
    '/pmk_environment',
]
#reload_cmd = 'supervisorctl restart resmgr'
