[template]
src = 'role_settings.conf'
dest = '/etc/pf9/resmgr_roles/conf.d/role_settings.conf'
owner = 'root'
mode = '0644'
keys = [
    '/services/resmgr/role_settings'
]
reload_cmd = 'supervisorctl restart resmgr'
